language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/shoecatalogue_test
node_js:  
  - "10.15.2"
before_script:
  - psql -c 'create database shoecatalogue_test;' -U postgres
  - psql -U postgres -d shoecatalogue_test -a -f tables.sql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5